# Project-relative paths 
input: "samplesheet.csv"
outdir: "results"

# Shared RSU reference resources (keep absolute)
genome: "GATK.GRCh38"
igenomes_base: "/home/groups/rsu/dauksaite_v/igenomes"

wes: true
intervals: "/home/groups/rsu/nf-core-variant-calling/Twist_WESwithRefSeq_umap_s100_70_no_blacklist_hg38_PAR_regions.bed"

# Toolset
tools: "deepvariant,haplotypecaller,freebayes,strelka,manta,tiddit,cnvkit,indexcov"

# Joint genotyping
joint_germline: true

