# Project-relative paths 
input: "samplesheet.csv"
outdir: "results"

# Shared RSU reference resources (keep absolute)
genome: "GATK.GRCh38"
igenomes_base: "/home/groups/rsu/dauksaite_v/igenomes"

wes: true
intervals: "/home/groups/rsu/dauksaite_v/resources/Twist_WESwithRefSeq_umap_s100_70_no_blacklist_hg38_PAR_regions.bed"

# Toolset
tools: "deepvariant,haplotypecaller,freebayes,strelka,manta,tiddit,cnvkit,indexcov,vep,snpeff,merge"

# Joint genotyping
joint_germline: true

# VEP cache 
vep_cache: "/home/groups/rsu/dauksaite_v/resources/sarek_cache/vep_cache"
vep_cache_version: 115
vep_genome: "GRCh38"
vep_species: "homo_sapiens"

# SnpEff cache 
snpeff_cache: "/home/groups/rsu/dauksaite_v/resources/sarek_cache/snpeff_cache"
snpeff_db: "GRCh38.99"

# -----------------------
# Extra VEP plugin annotations (uses your /resources/vep_data files)
# -----------------------

# SpliceAI plugin
vep_spliceai: true
spliceai_snv: "/home/groups/rsu/dauksaite_v/resources/vep_data/spliceai_scores.masked.snv.hg38.vep1.vcf.gz"
spliceai_snv_tbi: "/home/groups/rsu/dauksaite_v/resources/vep_data/spliceai_scores.masked.snv.hg38.vep1.vcf.gz.tbi"
spliceai_indel: "/home/groups/rsu/dauksaite_v/resources/vep_data/spliceai_scores.masked.indel.hg38.vep1.vcf.gz"
spliceai_indel_tbi: "/home/groups/rsu/dauksaite_v/resources/vep_data/spliceai_scores.masked.indel.hg38.vep1.vcf.gz.tbi"

# Mastermind plugin
vep_mastermind: true
mastermind_file: "/home/groups/rsu/dauksaite_v/resources/vep_data/mastermind_cited_variants_reference-2021.04.02-grch38.vcf.gz"

